server:
  port: 9999
mybatis:
    mapper-locations: classpath:mapper/*/*.xml
spring:
  application:
    name: process-service
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    history-level: audit
    db-identity-used: false
    db-history-used: true
    activityFontName: 宋体
    labelFontName: 宋体
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.dev.syf.com:3306/shengye_process?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&nullCatalogMeansCurrent=true
    username: sy
    password: rhYrE3r4wmb9
    filters: stat,wall,slf4j
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 6000
    maxPoolPreparedStatementPerConnectionSize: 20
    minEvictableIdleTimeMillis: 30000
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    useGlobalDataSourceStat: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select 'x'
  redis:
    database: 1
    sentinel:
      master: mymaster
      nodes: redis-sentinel-node1.dev.svc.k8s.syf.com:26379,redis-sentinel-node2.dev.svc.k8s.syf.com:26379,redis-sentinel-node3.dev.svc.k8s.syf.com:26379